### ISSUE TITLE
Wikipedia list of BO-ZH texts

### ISSUE THREAD

**Issue by ngawangtrinley** [The-Kumarajiva-Project/BO-to-ZH-TM#1]
- [x] Collect titles of texts that have both Tibetan and Chinese versions
- [ ] Create a Wikipedia article called "List of Tibetan to Chinese translations"
- [ ] Add list to the Wikipedia article
- [ ] Share list in social media and ask the public to contribute texts missing from the list

**Comment by sherabchen** [comment]
It sounds a great idea to create a Wikipedia page for Bo-Zh texts! However, I have a question. Does the "Chinese versions" in "Collect titles of texts that have both Tibetan and Chinese versions" mean old Chinese (i.e. canonical) translations? If so, then I feel the proposed Wikipedia title "List of Tibetan to Chinese translations" might be misleading - and I'd suggest "List of corresponding Tibetan and Chinese canonical translations" instead. Well, I might have misunderstood something :)

**Comment by StephYKW** [comment]
testing done.
